version: '3'
services:
  nodejs-app:
    image: 647797471572.dkr.ecr.eu-central-1.amazonaws.com/docker-demo:1.0
    container_name: nodejs-app 
    ports:
      - 3000:3000
    depends_on:
      - mongodb 
  mongodb:
    image: mongo 
    container_name: mongodb 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin \
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin123 \
      - MONGO_DB_USERNAME=mongoadmin \
      - MONGO_DB_PWD=mongoadmin123
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express 
    container_name: mongo-express 
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongoadmin123
      - ME_CONFIG_MONGODB_SERVER=mongodb 
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongodb 
